In [10]:
import numpy as np

arr1 = np.array([1,3,4,5])
arr2 = np.array([1,3,4,5])
id(arr1)
print(arr2)
arr2[3]=6
print(arr2)

[1 3 4 5]
[1 3 4 6]


In [13]:
arr4 = np.copy(arr1)
print(arr4)

[1 3 4 5]


In [14]:
arr6 = np.array({'A':1, 'B':2})
print(arr6)

{'A': 1, 'B': 2}


In [18]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.size)
print(len(a))

9
3


In [22]:
print(a.shape)
print(a.ndim)

(3, 3)
2


In [26]:
np.array([111,2.3,True])

array([111. ,   2.3,   1. ])

In [29]:
np.linspace(1,10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
li1 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(li1)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [46]:
np.zeros((2,3),dtype='int64')

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
a2 = np.arange(8)
print(a2)
a2.reshape(2,2,2)

[0 1 2 3 4 5 6 7]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [56]:
a3 = np.arange(15)
a3.shape = (5,3)
print(a3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [58]:
data = np.random.randn(2,3)
print(data)


[[-0.63772088 -1.64266672  0.07724804]
 [-0.56987474  1.40198503 -0.94237981]]


In [59]:
data2 = np.random.randn(100,100)
mean = np.mean(data2)
print(mean)

-0.00564566895703565


In [70]:
%time for i in range(100):np.arange(1000000)*2

CPU times: user 125 ms, sys: 2.77 ms, total: 128 ms
Wall time: 127 ms


In [69]:
%time for i in range(100):list(range(1000000))*2

CPU times: user 4.4 s, sys: 1.65 s, total: 6.06 s
Wall time: 6.32 s


In [74]:
a= [[2,2],[4,3]]
c= np.append(a,[[9],[9]], axis =1)
print(c)
print(np.delete(a,0))

[[2 2 9]
 [4 3 9]]
[2 4 3]


In [75]:
#@title 2x3 array of zeros, 3x2 array of ones
a = np.zeros((2,3))
print(a)
b = np.ones((3,2))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [76]:
#@title 5 equally spaced bumbers between 0 and 20 using linspace. Print array and type.
a = np.linspace(0,20,5)
print(a)
print(type(a))

[ 0.  5. 10. 15. 20.]
<class 'numpy.ndarray'>


In [78]:
#@title Create array [5,10,15,20]. Change second element to 100. Print updated array
a = np.array([5,10,15,20])
a[1] = 100
print(a)

[  5 100  15  20]


In [79]:
#@title Create 2x3 array. Create 1D array [10,20,30]. Add both arrays, print result
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
c = np.add(a,b)
print(c)

[[11 22 33]
 [14 25 36]]


In [82]:
#@title Create array [1,2,3]. Assign it to another variable. Modify new variable. show effect on original array.
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [81]:
#@title Create array [1,2,3]. Make a copy using .copy(). Modify copy. Show original is unchanged.
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)


[1 2 3]
[100   2   3]


In [83]:
a = np.arange(12)
print(a.reshape(3,4))
print(a.reshape(2,6))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [86]:
a = np.array([1, 2.5, 3])
b = a.astype(int)
print(b)
print (a)

[1 2 3]
[1.  2.5 3. ]


In [96]:
a = np.random.randint(1,10,(2,3))
print(a)
np.delete(a,0)

[[5 1 7]
 [1 8 2]]


array([1, 7, 1, 8, 2])

In [99]:
a = np.random.randint(1,10,(2,3))
print(a)
a= np.delete(a,0,axis=0)
np.delete(a,1,axis=1)


[[5 3 4]
 [5 5 1]]


array([[5, 1]])

In [102]:
a = np.random.randint(1,10,(2,3))
b = a.reshape(3,2)
b[1]=10


print(a)

[[ 7  1 10]
 [10  7  7]]


In [106]:
a = np.random.randint(1,10,(2,2,2))
print(a)
print(a.shape)
print(a.size)
print(len(a))
print(np.ndim(a))

[[[7 2]
  [7 1]]

 [[7 8]
  [4 1]]]
(2, 2, 2)
8
2
3


In [110]:
a = np.arange(1, 10, 5)
b = np.linspace(1, 10, 5)
print(a)
print(b)

[1 6]
[ 1.    3.25  5.5   7.75 10.  ]
