In [8]:
import numpy as np

a = np.random.rand(5)
print(a)
print(np.random.seed(123))

[0.9629972  0.42623558 0.71809435 0.71670981 0.311703  ]
None


In [7]:
while True:
  num = np.random.randint(1,11)
  print(num)
  if num ==10:
    break

1
6
7
10


In [22]:
np.random.seed(0)
print("First set of random numbers with seed 0:", np.random.rand(3))

np.random.seed(0)
print("Second set of random numbers with same seed 0:", np.random.rand(3))

print("Random numbers without a specific seed:", np.random.rand(3))

First set of random numbers with seed 0: [0.5488135  0.71518937 0.60276338]
Second set of random numbers with same seed 0: [0.5488135  0.71518937 0.60276338]
Random numbers without a specific seed: [0.54488318 0.4236548  0.64589411]


In [41]:
ran_seed = np.random.randint(100)
print(f"ran_seed: {ran_seed}")
np.random.seed(ran_seed)
a = np.random.randint(1, 11, 10)
print(a)
np.random.seed(ran_seed)
b = np.random.randint(1, 11, 10)
print(b)
c = np.random.randint(1, 11, 10)
print(c)

ran_seed: 16
[10 10  6  2  5  5 10  1  1  9]
[10 10  6  2  5  5 10  1  1  9]
[3 5 1 2 3 5 1 6 3 4]


In [43]:
b = np.round(np.var(a),2)
print(b)

12.49


In [83]:
z = np.random.randint(10, size = 5)
z = np.unique(z)
# z = set(z)
print(z)
arg_max = np.argmax(z)
print(z[arg_max])
arg_min = np.argmin(z)
print(z[arg_min])

[0 2 6 9]
9
0


In [86]:
A = np.array(np.random.randint(1,2,(2,2)))
print(A)
B = np.array(np.random.randint(1,10,(2,2)))
print(B)
print(A.dot(B))
print(A@B)

[[1 1]
 [1 1]]
[[6 7]
 [6 9]]
[[12 16]
 [12 16]]
[[12 16]
 [12 16]]


In [103]:
#@title Indexing multiple elements in an array
a = np.array([1,2,3,4,5])
a2 = np.arange(10,100,10).reshape(3,3)
print(a2[1])
a2[1]= [50,30,20]
print(a2)

[40 50 60]
[[10 20 30]
 [50 30 20]
 [70 80 90]]


In [108]:
a = np.array ([1,2,3,4,5])
b = np.array ([6,7,8,9,10])
print(a[a>3])
print(a[a==3])
print(a[a!=3])
print(a[::3])
print(a[1:4])

[4 5]
[3]
[1 2 4 5]
[1 4]
[2 3 4]


In [110]:
#@title Slicing multiple dimensional arrays
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20]])
b = a[::2, ::2]
print(b)

[[ 1  3  5]
 [11 13 15]]


In [121]:
a= np.empty((4,2))
print(a)
for i in range(4):
  print(a[i])

[[0.0e+000 4.9e-324]
 [9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323]
 [3.5e-323 4.0e-323]]
[0.e+000 5.e-324]
[9.9e-324 1.5e-323]
[2.0e-323 2.5e-323]
[3.5e-323 4.0e-323]


In [123]:
arr2 = np.arange(20)
arrMask = (arr2%5==0)
print(arrMask.astype(int))

[1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0]


In [132]:
a = np.array([[[1,2],[3,4]],
             [[6,7],[8,9]]])
print(a,"\n\n")
print(a.transpose())

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]] 


[[[1 6]
  [3 8]]

 [[2 7]
  [4 9]]]


In [136]:
a = np.array([[[1,2],[3,4]],
             [[6,7],[8,9]]])
print(a.swapaxes(0,1))

[[[1 2]
  [6 7]]

 [[3 4]
  [8 9]]]


In [138]:
#@title Extract elements from a 2d array such that: take every alternate row, take every alternate column
import numpy as np
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20]])
b = a[::2, ::2]
print(b)

[[ 1  3  5]
 [11 13 15]]


In [139]:
#@title From an array of numbers 0-20 extract values that are divsible by and greater than 10
import numpy as np
arr = np.arange(0, 21)
extracted_values = arr[(arr % 2 == 0) & (arr > 10)]
print(extracted_values)

[12 14 16 18 20]


In [140]:
#@title Slice an array, modeify the slice. Check whether original array changes
import numpy as np
original_array = np.array([1, 2, 3, 4, 5])
print("Original array before slicing and modification:", original_array)

sliced_array = original_array[1:4]
print("Sliced array (view of original):", sliced_array)

sliced_array[0] = 99

print("\nOriginal array after modifying slice:", original_array)
print("Sliced array after modification:", sliced_array)


Original array before slicing and modification: [1 2 3 4 5]
Sliced array (view of original): [2 3 4]

Original array after modifying slice: [ 1 99  3  4  5]
Sliced array after modification: [99  3  4]


In [141]:
#@title reverse a given array using slicing and extract last 3 elements
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original array:", arr)

reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

last_3_from_reversed = reversed_arr[-3:]
print("Last 3 elements from the reversed array:", last_3_from_reversed)

last_3_original_reversed = arr[:-4:-1]
print("Last 3 elements of original array, in reversed order:", last_3_original_reversed)

Original array: [10 20 30 40 50 60 70]
Reversed array: [70 60 50 40 30 20 10]
Last 3 elements from the reversed array: [30 20 10]
Last 3 elements of original array, in reversed order: [70 60 50]


In [142]:
#@title extract the last column from a 2d array
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Original 2D array:\n", matrix)

last_column = matrix[:, -1]
print("\nLast column extracted:\n", last_column)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Last column extracted:
 [3 6 9]


In [143]:
#@title create a 3x3 array using empty() and fill it with value 7
import numpy as np
arr = np.empty((3, 3))
arr.fill(7)
print(arr)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [144]:
#@title given a 2x3 array find transpose. resahpe into 3x2, compare results
import numpy as np
original = np.array([[1, 2, 3],
                     [4, 5, 6]])
print("Original 2x3 array:\n", original)

transposed = original.T
print("\nTransposed array (original.T):\n", transposed)

reshaped = original.reshape(3, 2)
print("\nReshaped array (original.reshape(3,2)):\n", reshaped)

print("\nAre transposed and reshaped arrays equal?:", np.array_equal(transposed, reshaped))

Original 2x3 array:
 [[1 2 3]
 [4 5 6]]

Transposed array (original.T):
 [[1 4]
 [2 5]
 [3 6]]

Reshaped array (original.reshape(3,2)):
 [[1 2]
 [3 4]
 [5 6]]

Are transposed and reshaped arrays equal?: False


In [145]:
#@title create a 3d array and swap axis 1 and 2
import numpy as np
arr_3d = np.arange(24).reshape(2, 3, 4)
print("Original 3D array (shape:", arr_3d.shape, "):\n", arr_3d)

swapped_arr = arr_3d.swapaxes(1, 2)
print("\nArray after swapping axes 1 and 2 (new shape:", swapped_arr.shape, "):\n", swapped_arr)

Original 3D array (shape: (2, 3, 4) ):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Array after swapping axes 1 and 2 (new shape: (2, 4, 3) ):
 [[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [151]:
#@title find index of maximum element in a 2d array
import numpy as np
arr_2d = np.array([[1, 5, 3],[8, 2, 9],[4, 7, 6]])
print("2D array:\n", arr_2d)


max_index = np.argmax(arr_2d)
print("\nIndex of maximum element", max_index)


2D array:
 [[1 5 3]
 [8 2 9]
 [4 7 6]]

Index of maximum element 5


In [147]:
#@title compute cumulative sum along rows
import numpy as np
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("Original array:\n", data)

cumulative_sum_rows = np.cumsum(data, axis=1)
print("\nCumulative sum along rows (axis=1):\n", cumulative_sum_rows)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Cumulative sum along rows (axis=1):
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
