#PYTHON MATRIX OPERATIONS USING NUMPY

- Matrices created using numpy.array()
- dot() or @ operator for matrix multiplication
- Transpose .T

In [ ]:
#@title Matrix multiplication
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A,B)
print(C)

#using @ operator
C = B@A
print(C)

#using matmul()
C = np.matmul(A,B)
print(C)

# * only brings element wise multiplication
C = A*B
print(C)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [ ]:
#@title Transpose of Matrix
import numpy as np

A = np.array([[1,2],[3,4]])
print(A)
print(A.T)
print(np.transpose(A))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [ ]:
#@title 3x3 matrix mult and transpose
import numpy as np

A = eval(input("Enter first matrix: "))
B = eval(input("Enter second matrix: "))

A = np.array(A)
B = np.array(B)
C = A@B

print(C)
print(C.T)

Enter first matrix: [1,2,3],[4,5,6],[6,7,8]
Enter second matrix: [1,2,3,5,6],[4,5,6,3,5],[6,7,8,6,2]
[[ 27  33  39  29  22]
 [ 60  75  90  71  61]
 [ 82 103 124  99  87]]
[[ 27  60  82]
 [ 33  75 103]
 [ 39  90 124]
 [ 29  71  99]
 [ 22  61  87]]


In [ ]:
#@title Random Matrix Generation
import numpy as np

R = np.random.rand(3,3)
print(R)

R = np.random.randint(3,10,(3,4))
print(R)

R = np.random.randn(3,3)
print(R)

R = np.random.uniform(3,10,(3,4))
print(R)

[[0.76979688 0.41681269 0.86993543]
 [0.13988668 0.2143614  0.19519986]
 [0.37283524 0.06760783 0.73407169]]
[[8 3 6 5]
 [8 8 4 4]
 [9 3 9 3]]
[[-1.06797441 -0.34957562  0.82086994]
 [ 1.61610624 -1.42780884  1.01275228]
 [-0.93882145 -1.13150595 -1.33654741]]
[[5.16111335 8.57548375 9.36271113 7.04046861]
 [5.99732087 7.80009998 7.46673325 7.02333243]
 [9.92721981 9.03250974 7.14335124 7.70225368]]


In [ ]:
#@title Square matrix
import numpy as np
n = int(input("Enter size of square matrix (n): "))
print("Enter elements row-wise: ")
elements=[]
for i in range(n):
  row = list(map(int,input().split()))
  elements.append(row)

A = np.array(elements)
print("Square Matrix: ",A)


Enter size of square matrix (n): 3
Enter elements row-wise: 
1
2
3
Square Matrix:  [[1]
 [2]
 [3]]


In [ ]:
#@title Diagonal Matrix(User input)
import numpy as np

n = int(input("Enter size of diagonal matrix (n): "))
print("Enter diagonal elements: ")
elements = list(map(int,input().split()))
D = np.diag(elements)
print("Diagonal Matrix: \n" ,D)

Enter size of diagonal matrix (n): 5
Enter diagonal elements: 
1 2 3 4 5
Diagonal Matrix: 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [1]:
#@title Unit matrix
import numpy as np
n= map(int,(input("Enter size of unit matrix (n)"))
unit_matrix = np.eye(n)
print("Unit Matrix: \n", unit_matrix)

Enter size of unit matrix (n)2
Unit Matrix: 
 [[1. 0.]
 [0. 1.]]


In [ ]:
#@title Symmetric Matrix

import numpy as np
n = int (input("Enter size of matrix(n): "))
print("Enter elements row-wise: ")
elements = []
for i in range (n):
  row = list(map(int, input().split()))
  elements.append(row)

matrix = np.array(elements)
print("Matrix: ", matrix)
if np.array_equal(matrix, matrix.T):
  print("Symmetric Matrix")
else:
  print("Not a Symmetric Matrix")

Enter size of matrix(n): 3
Enter elements row-wise: 
1 2 3
4 5 6
7 8 9
Matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Not a Symmetric Matrix


In [ ]:
import numpy as np
n = int (input("Enter size of matrix(n): "))
print("Enter elements row-wise: ")
elements = []
for i in range (n):
  row = list(map(int, input().split()))
  elements.append(row)

matrix = np.array(elements)
print(np.linalg.inv(matrix))

Enter size of matrix(n): 2
Enter elements row-wise: 
0 0
2 3


LinAlgError: Singular matrix

In [ ]:
import numpy as np
A = np.array([[1,-4],[-4,1]])
B = np.array([[2,-8],[-8,2]])
print("A+B= \n", A+B)
print("A-(1/2)B= \n", A-(1/2)*B)
print("5A= \n", 5*A)

A+B= 
 [[  3 -12]
 [-12   3]]
A-(1/2)B= 
 [[0. 0.]
 [0. 0.]]
5A= 
 [[  5 -20]
 [-20   5]]


In [ ]:
import numpy as np

A = np.array([[4,2],[1,3]])
eigen_values, eigen_vectors = np.linalg.eig(A)
print("Eigen Values: \n", eigen_values)
print("Eigen Vectors: \n", eigen_vectors)

Eigen Values: 
 [5. 2.]
Eigen Vectors: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
#@title Zero and One vector
import numpy as np
zero_vector = np.zeros(3)
print("zero vector: ", zero_vector)
one_vector = np.ones(4)
print("One vector: ", one_vector)

zero vector:  [0. 0. 0.]
One vector:  [1. 1. 1. 1.]


In [ ]:
#@title Differentiation
import sympy as sp
x = sp.symbols('x')
f = x**3 -1
sp.diff(f)

3*x**2

In [ ]:
import sympy as sp
x,k = sp.symbols('x k')
f = sp.log(x**2 - 3*k)
sp.diff(f,x)

2*x/(-3*k + x**2)

In [ ]:
import sympy as sp
x,a,b = sp.symbols('x a b')
f = sp.exp(a**2*b)
sp.simplify(sp.diff(f,x))

0

In [ ]:
import sympy as sp
x,a = sp.symbols('x a')
f = sp.sin(a*x**2)
sp.diff(f,x)

2*a*x*cos(a*x**2)

In [ ]:
import sympy as sp
x, k = sp.symbols('x k')
f = sp.log(sp.sin(k*x))
sp.diff(f,x)

k*cos(k*x)/sin(k*x)

In [ ]:
import sympy as sp

x,y = sp.symbols('x y')
f = sp.sin(x*y)+sp.cos(x+y)
print("fx = ",sp.diff(f,x))
print("fy = ",sp.diff(f,y))
print("fxx = ", sp.diff(f,x,x))
print("fxy = ", sp.diff(f,x,y))
print("fyy = ", sp.diff(f,y,y))

fx =  y*cos(x*y) - sin(x + y)
fy =  x*cos(x*y) - sin(x + y)
fxx =  -(y**2*sin(x*y) + cos(x + y))
fxy =  -x*y*sin(x*y) + cos(x*y) - cos(x + y)
fyy =  -(x**2*sin(x*y) + cos(x + y))


In [ ]:
import sympy as sp

x,y = sp.symbols('x y')
f = sp.exp(x**2+3*y**2)
print("fx = ",sp.diff(f,x))
print("fy = ",sp.diff(f,y))
print("fxx = ", sp.diff(f,x,x))
print("fxy = ", sp.diff(f,x,y))
print("fyy = ", sp.diff(f,y,y))

fx =  2*x*exp(x**2 + 3*y**2)
fy =  6*y*exp(x**2 + 3*y**2)
fxx =  2*(2*x**2 + 1)*exp(x**2 + 3*y**2)
fxy =  12*x*y*exp(x**2 + 3*y**2)
fyy =  6*(6*y**2 + 1)*exp(x**2 + 3*y**2)


In [ ]:
import sympy as sp

x,y = sp.symbols('x y')
f = sp.log(x**2+y**2+1)
print("fx = ",sp.diff(f,x))
print("fy = ",sp.diff(f,y))
print("fxx = ", sp.diff(f,x,x))
print("fxy = ", sp.diff(f,x,y))
print("fyy = ", sp.diff(f,y,y))

In [ ]:
import sympy as sp

x,y = sp.symbols('x y')
f = x**2*y + sp.exp(x*y)
print("fx = ",sp.diff(f,x))
print("fy = ",sp.diff(f,y))
print("fxx = ", sp.diff(f,x,x))
print("fxy = ", sp.diff(f,x,y))
print("fyy = ", sp.diff(f,y,y))

fx =  2*x*y + y*exp(x*y)
fy =  x**2 + x*exp(x*y)
fxx =  y*(y*exp(x*y) + 2)
fxy =  x*y*exp(x*y) + 2*x + exp(x*y)
fyy =  x**2*exp(x*y)
