##DataSet 1 :
Columns: Age, Salary, Experience, Department, Perfomance

In [ ]:
import numpy as np
data = np.genfromtxt('Emp_data.csv', delimiter = ',', skip_header = 1, dtype=str)
print(data)

[['25' '50000' '2' 'IT' '3']
 ['30' '60000' '5' 'HR' '4']
 ['22' '45000' '1' 'IT' '2']
 ['35' '80000' '10' 'Finance' '5']
 ['28' '52000' '3' 'IT' '3']
 ['40' '90000' '12' 'Finance' '5']
 ['29' '58000' '4' 'HR' '4']
 ['31' '62000' '6' 'IT' '4']
 ['27' '48000' '2' 'Marketing' '3']
 ['45' '100000' '15' 'Finance' '5']
 ['38' '75000' '9' 'IT' '4']
 ['26' '51000' '3' 'Marketing' '3']
 ['33' '67000' '7' 'HR' '4']
 ['24' '47000' '1' 'IT' '2']
 ['36' '82000' '11' 'Finance' '5']
 ['32' '64000' '6' 'IT' '4']
 ['41' '91000' '13' 'Finance' '5']
 ['23' '46000' '1' 'Marketing' '2']
 ['37' '78000' '8' 'IT' '4']
 ['34' '72000' '7' 'HR' '4']
 ['39' '85000' '10' 'Finance' '5']
 ['21' '42000' '0' 'IT' '1']
 ['28' '53000' '3' 'Marketing' '3']
 ['42' '92000' '14' 'Finance' '5']
 ['30' '61000' '5' 'HR' '4']
 ['27' '49000' '2' 'IT' '3']
 ['35' '81000' '10' 'Finance' '5']
 ['29' '57000' '4' 'Marketing' '3']
 ['31' '63000' '6' 'IT' '4']
 ['44' '98000' '14' 'Finance' '5']
 ['36' '83000' '11' 'HR' '5']
 ['25' '51

In [ ]:
age = data[::,0].astype(int)
salary = data[::,1].astype(float)
experience = data[::,2].astype(float)
performance = data[::,4].astype(float)
print(age)
print(salary)
print(experience)
print(performance)

[25 30 22 35 28 40 29 31 27 45 38 26 33 24 36 32 41 23 37 34 39 21 28 42
 30 27 35 29 31 44 36 25 33 38 26 40 28 37 34 43 22 39 27 32 41 24 36 30
 35 29]
[ 50000.  60000.  45000.  80000.  52000.  90000.  58000.  62000.  48000.
 100000.  75000.  51000.  67000.  47000.  82000.  64000.  91000.  46000.
  78000.  72000.  85000.  42000.  53000.  92000.  61000.  49000.  81000.
  57000.  63000.  98000.  83000.  51000.  68000.  76000.  52000.  89000.
  54000.  79000.  71000.  95000.  44000.  86000.  50000.  65000.  93000.
  48000.  84000.  60000.  80000.  56000.]
[ 2.  5.  1. 10.  3. 12.  4.  6.  2. 15.  9.  3.  7.  1. 11.  6. 13.  1.
  8.  7. 10.  0.  3. 14.  5.  2. 10.  4.  6. 14. 11.  2.  7.  9.  3. 12.
  3.  8.  7. 13.  1. 10.  2.  6. 13.  1. 11.  5. 10.  4.]
[3. 4. 2. 5. 3. 5. 4. 4. 3. 5. 4. 3. 4. 2. 5. 4. 5. 2. 4. 4. 5. 1. 3. 5.
 4. 3. 5. 3. 4. 5. 5. 3. 4. 4. 3. 5. 3. 4. 4. 5. 2. 5. 3. 4. 5. 2. 5. 4.
 5. 3.]


In [ ]:
department = data[::,3].astype(str)
print(department)

['IT' 'HR' 'IT' 'Finance' 'IT' 'Finance' 'HR' 'IT' 'Marketing' 'Finance'
 'IT' 'Marketing' 'HR' 'IT' 'Finance' 'IT' 'Finance' 'Marketing' 'IT' 'HR'
 'Finance' 'IT' 'Marketing' 'Finance' 'HR' 'IT' 'Finance' 'Marketing' 'IT'
 'Finance' 'HR' 'IT' 'Marketing' 'Finance' 'IT' 'Finance' 'HR' 'IT'
 'Marketing' 'Finance' 'IT' 'Finance' 'Marketing' 'HR' 'Finance' 'IT'
 'Finance' 'IT' 'HR' 'Marketing']


In [ ]:
print("Shape",data.shape)

Shape (50, 5)


In [ ]:
print("Mean Salary: ", np.mean(salary))
print("Median Salary: ", np.median(salary))
print("Std Dev: ", np.std(salary))

Mean Salary:  67660.0
Median Salary:  64500.0
Std Dev:  16770.939150804883


In [ ]:
print(f"Minimum salary: {np.min(salary)} , Maximum salary: {np.max(salary)}")


Minimum salary: 42000.0 , Maximum salary: 100000.0


In [ ]:
high_salary = data[salary>70000]
print(high_salary)
high_salary.ndim

[['35' '80000' '10' 'Finance' '5']
 ['40' '90000' '12' 'Finance' '5']
 ['45' '100000' '15' 'Finance' '5']
 ['38' '75000' '9' 'IT' '4']
 ['36' '82000' '11' 'Finance' '5']
 ['41' '91000' '13' 'Finance' '5']
 ['37' '78000' '8' 'IT' '4']
 ['34' '72000' '7' 'HR' '4']
 ['39' '85000' '10' 'Finance' '5']
 ['42' '92000' '14' 'Finance' '5']
 ['35' '81000' '10' 'Finance' '5']
 ['44' '98000' '14' 'Finance' '5']
 ['36' '83000' '11' 'HR' '5']
 ['38' '76000' '9' 'Finance' '4']
 ['40' '89000' '12' 'Finance' '5']
 ['37' '79000' '8' 'IT' '4']
 ['34' '71000' '7' 'Marketing' '4']
 ['43' '95000' '13' 'Finance' '5']
 ['39' '86000' '10' 'Finance' '5']
 ['41' '93000' '13' 'Finance' '5']
 ['36' '84000' '11' 'Finance' '5']
 ['35' '80000' '10' 'HR' '5']]


2

In [ ]:
filtered_data = data[(salary>60000)& (experience>5)]
print(filtered_data)

[['35' '80000' '10' 'Finance' '5']
 ['40' '90000' '12' 'Finance' '5']
 ['31' '62000' '6' 'IT' '4']
 ['45' '100000' '15' 'Finance' '5']
 ['38' '75000' '9' 'IT' '4']
 ['33' '67000' '7' 'HR' '4']
 ['36' '82000' '11' 'Finance' '5']
 ['32' '64000' '6' 'IT' '4']
 ['41' '91000' '13' 'Finance' '5']
 ['37' '78000' '8' 'IT' '4']
 ['34' '72000' '7' 'HR' '4']
 ['39' '85000' '10' 'Finance' '5']
 ['42' '92000' '14' 'Finance' '5']
 ['35' '81000' '10' 'Finance' '5']
 ['31' '63000' '6' 'IT' '4']
 ['44' '98000' '14' 'Finance' '5']
 ['36' '83000' '11' 'HR' '5']
 ['33' '68000' '7' 'Marketing' '4']
 ['38' '76000' '9' 'Finance' '4']
 ['40' '89000' '12' 'Finance' '5']
 ['37' '79000' '8' 'IT' '4']
 ['34' '71000' '7' 'Marketing' '4']
 ['43' '95000' '13' 'Finance' '5']
 ['39' '86000' '10' 'Finance' '5']
 ['32' '65000' '6' 'HR' '4']
 ['41' '93000' '13' 'Finance' '5']
 ['36' '84000' '11' 'Finance' '5']
 ['35' '80000' '10' 'HR' '5']]


In [ ]:
it_employees = data[(department == 'IT')]
print(it_employees)

[['25' '50000' '2' 'IT' '3']
 ['22' '45000' '1' 'IT' '2']
 ['28' '52000' '3' 'IT' '3']
 ['31' '62000' '6' 'IT' '4']
 ['38' '75000' '9' 'IT' '4']
 ['24' '47000' '1' 'IT' '2']
 ['32' '64000' '6' 'IT' '4']
 ['37' '78000' '8' 'IT' '4']
 ['21' '42000' '0' 'IT' '1']
 ['27' '49000' '2' 'IT' '3']
 ['31' '63000' '6' 'IT' '4']
 ['25' '51000' '2' 'IT' '3']
 ['26' '52000' '3' 'IT' '3']
 ['37' '79000' '8' 'IT' '4']
 ['22' '44000' '1' 'IT' '2']
 ['24' '48000' '1' 'IT' '2']
 ['30' '60000' '5' 'IT' '4']]


In [ ]:
outliers = salary[salary>90000]
print(outliers)

[100000.  91000.  92000.  98000.  95000.  93000.]


In [ ]:
norm_salary = (salary - np.mean(salary))/np.std(salary)
print(norm_salary)

[-1.05301199 -0.45674246 -1.35114675  0.7357966  -0.93375808  1.33206613
 -0.57599637 -0.33748855 -1.1722659   1.92833566  0.43766183 -0.99338504
 -0.03935379 -1.23189285  0.85505051 -0.21823465  1.39169308 -1.2915198
  0.61654269  0.25878098  1.03393136 -1.53002761 -0.87413113  1.45132004
 -0.39711551 -1.11263894  0.79542355 -0.63562332 -0.2778616   1.80908175
  0.91467746 -0.99338504  0.02027316  0.49728879 -0.93375808  1.27243918
 -0.81450418  0.67616965  0.19915402  1.63020089 -1.41077371  1.09355832
 -1.05301199 -0.15860769  1.51094699 -1.1722659   0.97430441 -0.45674246
  0.7357966  -0.69525027]


In [ ]:
corr = np.corrcoef(salary,experience)
print(corr)

[[1.         0.99211731]
 [0.99211731 1.        ]]


In [ ]:
salary_exp = salary/(experience+1)
print(salary_exp)

[16666.66666667 10000.         22500.          7272.72727273
 13000.          6923.07692308 11600.          8857.14285714
 16000.          6250.          7500.         12750.
  8375.         23500.          6833.33333333  9142.85714286
  6500.         23000.          8666.66666667  9000.
  7727.27272727 42000.         13250.          6133.33333333
 10166.66666667 16333.33333333  7363.63636364 11400.
  9000.          6533.33333333  6916.66666667 17000.
  8500.          7600.         13000.          6846.15384615
 13500.          8777.77777778  8875.          6785.71428571
 22000.          7818.18181818 16666.66666667  9285.71428571
  6642.85714286 24000.          7000.         10000.
  7272.72727273 11200.        ]


In [ ]:
X = np.column_stack((age,experience))
y = salary
print(X)
print(y)

[[25.  2.]
 [30.  5.]
 [22.  1.]
 [35. 10.]
 [28.  3.]
 [40. 12.]
 [29.  4.]
 [31.  6.]
 [27.  2.]
 [45. 15.]
 [38.  9.]
 [26.  3.]
 [33.  7.]
 [24.  1.]
 [36. 11.]
 [32.  6.]
 [41. 13.]
 [23.  1.]
 [37.  8.]
 [34.  7.]
 [39. 10.]
 [21.  0.]
 [28.  3.]
 [42. 14.]
 [30.  5.]
 [27.  2.]
 [35. 10.]
 [29.  4.]
 [31.  6.]
 [44. 14.]
 [36. 11.]
 [25.  2.]
 [33.  7.]
 [38.  9.]
 [26.  3.]
 [40. 12.]
 [28.  3.]
 [37.  8.]
 [34.  7.]
 [43. 13.]
 [22.  1.]
 [39. 10.]
 [27.  2.]
 [32.  6.]
 [41. 13.]
 [24.  1.]
 [36. 11.]
 [30.  5.]
 [35. 10.]
 [29.  4.]]
[ 50000.  60000.  45000.  80000.  52000.  90000.  58000.  62000.  48000.
 100000.  75000.  51000.  67000.  47000.  82000.  64000.  91000.  46000.
  78000.  72000.  85000.  42000.  53000.  92000.  61000.  49000.  81000.
  57000.  63000.  98000.  83000.  51000.  68000.  76000.  52000.  89000.
  54000.  79000.  71000.  95000.  44000.  86000.  50000.  65000.  93000.
  48000.  84000.  60000.  80000.  56000.]


##DataSet 2 :
Columns: StudyHours, Attendance, Marks, SleepHours


In [ ]:
import numpy as np

data = np.genfromtxt('Student.csv', delimiter = ',', skip_header = 1, dtype=str)
print(data)

[['2' '75' '55' '6']
 ['4' '80' '65' '7']
 ['6' '85' '75' '6']
 ['8' '90' '85' '8']
 ['1' '60' '40' '5']
 ['3' '70' '50' '6']
 ['5' '88' '70' '7']
 ['7' '92' '88' '8']
 ['2' '65' '48' '6']
 ['6' '87' '78' '7']
 ['4' '82' '68' '6']
 ['5' '85' '72' '7']
 ['3' '75' '58' '6']
 ['7' '90' '82' '8']
 ['8' '95' '90' '8']
 ['2' '68' '52' '5']
 ['6' '88' '80' '7']
 ['5' '84' '74' '6']
 ['3' '72' '60' '6']
 ['7' '91' '85' '8']
 ['1' '58' '38' '5']
 ['2' '62' '45' '6']
 ['3' '70' '55' '6']
 ['4' '78' '62' '7']
 ['5' '83' '70' '7']
 ['6' '86' '76' '7']
 ['7' '90' '84' '8']
 ['8' '94' '91' '8']
 ['2' '66' '49' '6']
 ['3' '74' '57' '6']
 ['4' '80' '66' '7']
 ['5' '85' '73' '7']
 ['6' '89' '79' '7']
 ['7' '92' '87' '8']
 ['1' '55' '35' '5']
 ['2' '63' '47' '6']
 ['3' '71' '56' '6']
 ['4' '79' '64' '7']
 ['5' '84' '71' '7']
 ['6' '88' '77' '7']
 ['7' '91' '86' '8']
 ['8' '96' '93' '8']
 ['2' '67' '50' '6']
 ['3' '73' '59' '6']
 ['4' '81' '67' '7']
 ['5' '86' '75' '7']
 ['6' '90' '81' '7']
 ['7' '93' '8

In [ ]:
study_hours = data[::,0].astype(float)
attendance = data[::,1].astype(float)
marks = data[::,2].astype(float)
sleep_hours = data[::,3].astype(float)
print(study_hours)
print(attendance)
print(marks)
print(sleep_hours)

[2. 4. 6. 8. 1. 3. 5. 7. 2. 6. 4. 5. 3. 7. 8. 2. 6. 5. 3. 7. 1. 2. 3. 4.
 5. 6. 7. 8. 2. 3. 4. 5. 6. 7. 1. 2. 3. 4. 5. 6. 7. 8. 2. 3. 4. 5. 6. 7.
 1. 8.]
[75. 80. 85. 90. 60. 70. 88. 92. 65. 87. 82. 85. 75. 90. 95. 68. 88. 84.
 72. 91. 58. 62. 70. 78. 83. 86. 90. 94. 66. 74. 80. 85. 89. 92. 55. 63.
 71. 79. 84. 88. 91. 96. 67. 73. 81. 86. 90. 93. 57. 97.]
[55. 65. 75. 85. 40. 50. 70. 88. 48. 78. 68. 72. 58. 82. 90. 52. 80. 74.
 60. 85. 38. 45. 55. 62. 70. 76. 84. 91. 49. 57. 66. 73. 79. 87. 35. 47.
 56. 64. 71. 77. 86. 93. 50. 59. 67. 75. 81. 89. 37. 95.]
[6. 7. 6. 8. 5. 6. 7. 8. 6. 7. 6. 7. 6. 8. 8. 5. 7. 6. 6. 8. 5. 6. 6. 7.
 7. 7. 8. 8. 6. 6. 7. 7. 7. 8. 5. 6. 6. 7. 7. 7. 8. 8. 6. 6. 7. 7. 7. 8.
 5. 8.]


In [ ]:
mean = np.mean(marks)
print("Mean: ", mean)
median = np.median(marks)
print("Median: ", median)
std_dev = np.std(marks)
print("Std Dev: ", std_dev)


Mean:  67.78
Median:  70.0
Std Dev:  16.170701901896532


In [ ]:
cor_studyhours_marks = np.corrcoef(study_hours,marks)
print(cor_studyhours_marks)
cor_attendance_marks = np.corrcoef(attendance,marks)
print(cor_attendance_marks)

[[1.         0.98339369]
 [0.98339369 1.        ]]
[[1.         0.98702048]
 [0.98702048 1.        ]]


In [ ]:
norm_marks = (marks - np.mean(marks))/np.std(marks)
print(norm_marks)

[-0.7903182  -0.17191585  0.44648649  1.06488884 -1.71792172 -1.09951937
  0.13728532  1.25040954 -1.22319984  0.6320072   0.01360485  0.26096579
 -0.60479749  0.87936814  1.37409001 -0.9758389   0.75568767  0.38464626
 -0.48111703  1.06488884 -1.84160219 -1.40872055 -0.7903182  -0.35743656
  0.13728532  0.50832673  1.00304861  1.43593025 -1.16135961 -0.66663773
 -0.11007562  0.32280602  0.69384743  1.18856931 -2.02712289 -1.28504008
 -0.72847796 -0.23375609  0.19912556  0.57016696  1.12672908  1.55961072
 -1.09951937 -0.54295726 -0.04823538  0.44648649  0.8175279   1.31224978
 -1.90344242  1.68329119]


In [ ]:
marks_per_studyhour = marks/study_hours
print(marks_per_studyhour)

[27.5        16.25       12.5        10.625      40.         16.66666667
 14.         12.57142857 24.         13.         17.         14.4
 19.33333333 11.71428571 11.25       26.         13.33333333 14.8
 20.         12.14285714 38.         22.5        18.33333333 15.5
 14.         12.66666667 12.         11.375      24.5        19.
 16.5        14.6        13.16666667 12.42857143 35.         23.5
 18.66666667 16.         14.2        12.83333333 12.28571429 11.625
 25.         19.66666667 16.75       15.         13.5        12.71428571
 37.         11.875     ]


In [ ]:
top_students = data[marks>90]
print(top_students)

[['8' '94' '91' '8']
 ['8' '96' '93' '8']
 ['8' '97' '95' '8']]


##DataSet - 3
Columns: Size, Sqft, Bedrooms, Age, Price

In [ ]:
import numpy as np

data = np.genfromtxt("House.csv", delimiter = ',', skip_header = 1, dtype=str )
print(data)

[['1' '600' '1' '10' '200000']
 ['2' '800' '2' '8' '300000']
 ['3' '1200' '3' '5' '500000']
 ['2' '900' '2' '7' '320000']
 ['4' '1500' '4' '3' '650000']
 ['3' '1100' '3' '6' '480000']
 ['1' '500' '1' '12' '180000']
 ['2' '850' '2' '9' '310000']
 ['4' '1600' '4' '2' '700000']
 ['3' '1300' '3' '4' '550000']
 ['2' '780' '2' '10' '290000']
 ['3' '1150' '3' '6' '470000']
 ['1' '550' '1' '11' '190000']
 ['4' '1700' '4' '2' '720000']
 ['2' '820' '2' '8' '305000']
 ['3' '1250' '3' '5' '520000']
 ['1' '600' '1' '9' '210000']
 ['4' '1550' '4' '3' '680000']
 ['2' '880' '2' '7' '315000']
 ['3' '1400' '3' '4' '560000']
 ['1' '520' '1' '13' '175000']
 ['2' '760' '2' '10' '285000']
 ['3' '1180' '3' '6' '490000']
 ['4' '1650' '4' '2' '710000']
 ['2' '840' '2' '9' '300000']
 ['3' '1350' '3' '5' '540000']
 ['1' '580' '1' '11' '195000']
 ['4' '1720' '4' '2' '730000']
 ['2' '810' '2' '8' '295000']
 ['3' '1280' '3' '6' '510000']
 ['1' '540' '1' '12' '185000']
 ['2' '870' '2' '9' '305000']
 ['3' '1220' '3' 

In [39]:
size = data[::,0].astype(int)
sqft = data[::,1].astype(float)
bedrooms = data[::,2].astype(int)
age = data[::,3].astype(int)
price = data[::,4].astype(float)

print("Size:", size)
print("Sqft:", sqft)
print("Bedrooms:", bedrooms)
print("Age:", age)
print("Price:", price)

Size: [1 2 3 2 4 3 1 2 4 3 2 3 1 4 2 3 1 4 2 3 1 2 3 4 2 3 1 4 2 3 1 2 3 4 2 3 1
 4 2 3 1 2 3 4 2 3 1 4 2 3]
Sqft: [ 600.  800. 1200.  900. 1500. 1100.  500.  850. 1600. 1300.  780. 1150.
  550. 1700.  820. 1250.  600. 1550.  880. 1400.  520.  760. 1180. 1650.
  840. 1350.  580. 1720.  810. 1280.  540.  870. 1220. 1600.  890. 1380.
  560. 1680.  830. 1320.  510.  780. 1190. 1620.  860. 1450.  590. 1750.
  800. 1250.]
Bedrooms: [1 2 3 2 4 3 1 2 4 3 2 3 1 4 2 3 1 4 2 3 1 2 3 4 2 3 1 4 2 3 1 2 3 4 2 3 1
 4 2 3 1 2 3 4 2 3 1 4 2 3]
Age: [10  8  5  7  3  6 12  9  2  4 10  6 11  2  8  5  9  3  7  4 13 10  6  2
  9  5 11  2  8  6 12  9  5  3  7  4 10  2  8  5 13  9  6  3  8  4 10  2
  9  5]
Price: [200000. 300000. 500000. 320000. 650000. 480000. 180000. 310000. 700000.
 550000. 290000. 470000. 190000. 720000. 305000. 520000. 210000. 680000.
 315000. 560000. 175000. 285000. 490000. 710000. 300000. 540000. 195000.
 730000. 295000. 510000. 185000. 305000. 500000. 690000. 320000. 555000.
 200000.

In [40]:
mean_price = np.mean(price)
median_price = np.median(price)
std_dev_price = np.std(price)

print("Mean Price:", mean_price)
print("Median Price:", median_price)
print("Standard Deviation Price:", std_dev_price)

Mean Price: 425500.0
Median Price: 395000.0
Standard Deviation Price: 184700.43313430535


In [41]:
above_average_houses = data[price > mean_price]
print("Houses above average price:")
print(above_average_houses)

Houses above average price:
[['3' '1200' '3' '5' '500000']
 ['4' '1500' '4' '3' '650000']
 ['3' '1100' '3' '6' '480000']
 ['4' '1600' '4' '2' '700000']
 ['3' '1300' '3' '4' '550000']
 ['3' '1150' '3' '6' '470000']
 ['4' '1700' '4' '2' '720000']
 ['3' '1250' '3' '5' '520000']
 ['4' '1550' '4' '3' '680000']
 ['3' '1400' '3' '4' '560000']
 ['3' '1180' '3' '6' '490000']
 ['4' '1650' '4' '2' '710000']
 ['3' '1350' '3' '5' '540000']
 ['4' '1720' '4' '2' '730000']
 ['3' '1280' '3' '6' '510000']
 ['3' '1220' '3' '5' '500000']
 ['4' '1600' '4' '3' '690000']
 ['3' '1380' '3' '4' '555000']
 ['4' '1680' '4' '2' '720000']
 ['3' '1320' '3' '5' '530000']
 ['3' '1190' '3' '6' '495000']
 ['4' '1620' '4' '3' '700000']
 ['3' '1450' '3' '4' '570000']
 ['4' '1750' '4' '2' '740000']
 ['3' '1250' '3' '5' '515000']]


In [42]:
corr_sqft_price = np.corrcoef(sqft, price)
print("Correlation between Square Footage and Price:")
print(corr_sqft_price)

corr_bedrooms_price = np.corrcoef(bedrooms, price)
print("Correlation between Bedrooms and Price:")
print(corr_bedrooms_price)

Correlation between Square Footage and Price:
[[1.         0.99648132]
 [0.99648132 1.        ]]
Correlation between Bedrooms and Price:
[[1.         0.98461588]
 [0.98461588 1.        ]]


In [43]:
norm_price = (price - mean_price) / std_dev_price
print("Normalized Price:")
print(norm_price)

Normalized Price:
[-1.22089589 -0.67947864  0.40335585 -0.5711952   1.21548172  0.2950724
 -1.32917934 -0.62533692  1.48619034  0.67406447 -0.73362037  0.24093067
 -1.27503762  1.59447379 -0.65240778  0.5116393  -1.16675417  1.37790689
 -0.59826606  0.7282062  -1.3562502  -0.76069123  0.34921412  1.54033207
 -0.67947864  0.61992275 -1.24796675  1.64861552 -0.70654951  0.45749757
 -1.30210848 -0.65240778  0.40335585  1.43204862 -0.5711952   0.70113533
 -1.22089589  1.59447379 -0.67947864  0.56578102 -1.38332107 -0.73362037
  0.37628499  1.48619034 -0.62533692  0.78234792 -1.19382503  1.70275724
 -0.70654951  0.48456844]


In [44]:
price_per_sqft = price / sqft
print("Price per Square Foot:")
print(price_per_sqft)

Price per Square Foot:
[333.33333333 375.         416.66666667 355.55555556 433.33333333
 436.36363636 360.         364.70588235 437.5        423.07692308
 371.79487179 408.69565217 345.45454545 423.52941176 371.95121951
 416.         350.         438.70967742 357.95454545 400.
 336.53846154 375.         415.25423729 430.3030303  357.14285714
 400.         336.20689655 424.41860465 364.19753086 398.4375
 342.59259259 350.57471264 409.83606557 431.25       359.5505618
 402.17391304 357.14285714 428.57142857 361.44578313 401.51515152
 333.33333333 371.79487179 415.96638655 432.09876543 360.46511628
 393.10344828 347.45762712 422.85714286 368.75       412.        ]


In [49]:

expensive_houses = data[price > 600000]
print("Expensive houses (price > 600000):")
print(expensive_houses)

Expensive houses (price > 600000):
[['4' '1500' '4' '3' '650000']
 ['4' '1600' '4' '2' '700000']
 ['4' '1700' '4' '2' '720000']
 ['4' '1550' '4' '3' '680000']
 ['4' '1650' '4' '2' '710000']
 ['4' '1720' '4' '2' '730000']
 ['4' '1600' '4' '3' '690000']
 ['4' '1680' '4' '2' '720000']
 ['4' '1620' '4' '3' '700000']
 ['4' '1750' '4' '2' '740000']]


In [51]:
import pandas as pd

df = pd.read_csv("titanic.csv")
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                             

In [53]:
print(df.head())
print(df.tail())
print(df.info())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
  

In [69]:
print(df['Age'],df['Fare'])

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64 0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64


In [72]:
df.rename(columns={'Pclass':'class'}, inplace = True)
print(df)

     PassengerId  Survived  class  \
0              1         0      3   
1              2         1      1   
2              3         1      3   
3              4         1      1   
4              5         0      3   
..           ...       ...    ...   
886          887         0      2   
887          888         1      1   
888          889         0      3   
889          890         1      1   
890          891         0      3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
88

In [91]:
import pandas as pd
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv'
df = pd.read_csv(url)

print(type(df))
print(df.head())
print(df.tail())
print(df.info())

print(df.columns)
print(df.index)

df.rename(columns={'sepal_length':'SepalLength'}, inplace = True)
print(df['SepalLength'])
print(df[['SepalLength', 'petal_length']])

print(df.head(1))
print(df.head(1)['SepalLength'])

<class 'pandas.core.frame.DataFrame'>
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------      