In [ ]:
import numpy as np

sentences = [
    "i love ai",
    "i love coding",
    "i enjoy ai",
    "ai is fun",
    "coding is fun"
]

words = list(set(" ".join(sentences).split()))
word_to_id = {w: i for i, w in enumerate(words)}
id_to_word = {i: w for w, i in word_to_id.items()}

print(word_to_id)

training_data = []

for sentence in sentences:
    tokens = sentence.split()
    for i in range(len(tokens) - 1):
        input_word = tokens[i]
        target_word = tokens[i + 1]
        training_data.append((input_word, target_word))

print(training_data)

vocab_size = len(words)
embedding_dim = 5

# random vectors for each word
embeddings = np.random.rand(vocab_size, embedding_dim)
print(embeddings)
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def predict(word):
    word_id = word_to_id[word]
    word_vec = embeddings[word_id]

    similarities = []

    for i in range(vocab_size):
        if i == word_id:
            similarities.append(-1)  # ignore itself
            continue

        sim = cosine_similarity(word_vec, embeddings[i])
        similarities.append(sim)

    predicted_id = np.argmax(similarities)
    return id_to_word[predicted_id]

print(predict("i"))
print(predict("love"))

learning_rate = 0.01

for epoch in range(500):
    for input_word, target_word in training_data:
        input_id = word_to_id[input_word]
        target_id = word_to_id[target_word]

        input_vec = embeddings[input_id]
        target_vec = embeddings[target_id]

        # move input vector closer to target
        embeddings[input_id] += learning_rate * (target_vec - input_vec)

print(predict("i"))     # should give "love" or "enjoy"
print(predict("love"))  # should give "ai" or "coding"

{'love': 0, 'ai': 1, 'fun': 2, 'coding': 3, 'enjoy': 4, 'is': 5, 'i': 6}
[('i', 'love'), ('love', 'ai'), ('i', 'love'), ('love', 'coding'), ('i', 'enjoy'), ('enjoy', 'ai'), ('ai', 'is'), ('is', 'fun'), ('coding', 'is'), ('is', 'fun')]
[[0.87102565 0.7793403  0.7141081  0.64003855 0.22747587]
 [0.38528966 0.03917632 0.43505627 0.28656111 0.57437871]
 [0.24825875 0.07709718 0.62852669 0.46906231 0.4103524 ]
 [0.34807322 0.41183228 0.70919353 0.24689671 0.748682  ]
 [0.28788017 0.76627184 0.31086537 0.54204955 0.48659141]
 [0.02471809 0.90879059 0.67196789 0.99124425 0.88621312]
 [0.85430205 0.02363338 0.51417647 0.85355156 0.70512725]]
ai
enjoy
enjoy
coding
